// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwdzrrhjjrnruyfyydmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3ZHpycmhqanJucnV5Znl5ZG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MzM3MTUsImV4cCI6MjA1NTAwOTcxNX0.PqIqw0FYqEIvuPEBHYFut0KViP1OpmzZzxbBvFhGdSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
